### ISSUE TITLE
Could find json file

### ISSUE THREAD

**Issue by bdviett** [joeperpetua/Jisho-ESP#1]
/translate_modules/DJaponES-90604793006c.json

I could find this file. Can you help me?
![image](https://user-images.githubusercontent.com/25724001/124639231-1e60b300-deb6-11eb-814f-20fa0deed16d.png)

**Comment by joeperpetua** [comment]
That is the Google Translate API file, you should generate your own in the Google Cloud Console.

You have to setup your environment for the translate API, you can check the Google documentation: https://cloud.google.com/translate/docs/setup

For the specific json file you mention, you can check this section: https://cloud.google.com/translate/docs/setup#creating_service_accounts_and_keys

**Comment by ds-v-bui** [comment]
Are you tell me format of json file, I alreadly api_key

**Comment by bdviett** [comment]
I already json key file, but have same error

**Comment by joeperpetua** [comment]
Hi, 
On the file [/translate_modules/translate.js](https://github.com/joeperpetua/djapones-api/blob/master/translate_modules/translate.js) you have to set the path to you json file, it actually is pointing to an unexisting file, that is why it throws an error.

Check on line 5, the variable keyFilename:
`const keyFilename = './translate_modules/DJaponES-90604793006c.json';`

It should be changed to the path where you store you API key as:
`const keyFilename = './PATH/FILE.json';`

Also remember to change the project name (line 2), it should be match the project ID you have set in Google Cloud Console:

![image](https://user-images.githubusercontent.com/43834198/124652248-46c6be00-de72-11eb-9889-e075d1aa2694.png)

`const projectId = 'djapones';`

It should be changed to:
`const projectId = 'YOURPROJECTID';`

Hope this info helps

**Comment by bdviett** [comment]
Thank you.

**Comment by bdviett** [comment]
I don't have credit card so not enable translate api. Do you have options something else?
